# Generated by Django 4.0.6 on 2022-08-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0002_blog_carousel_category_product_subscribe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
