# Generated by Django 4.0.6 on 2022-08-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0003_alter_myuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
