# Generated by Django 4.0.6 on 2022-08-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0006_alter_arrival_arrivals_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
    ]
