# Generated by Django 4.0.6 on 2022-08-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0009_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
