# Generated by Django 4.0.6 on 2022-08-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0010_remove_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='custum_user',
        ),
    ]
