# Generated by Django 4.0.6 on 2022-08-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0012_rename_custum_user_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='custom_user',
        ),
    ]
