# Generated by Django 4.0.6 on 2022-08-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0020_alter_profile_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_number',
            field=models.CharField(blank=True, max_length=19),
        ),
    ]
