# Generated by Django 4.0.6 on 2022-08-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0021_alter_profile_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_number',
            field=models.IntegerField(blank=True, max_length=19),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.IntegerField(blank=True, max_length=200),
        ),
    ]
