# Generated by Django 4.0.6 on 2022-08-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0022_alter_profile_card_number_alter_profile_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_number',
            field=models.IntegerField(blank=True, default=1660),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.IntegerField(blank=True, default=998),
        ),
    ]
