# Generated by Django 4.0.6 on 2022-08-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0023_alter_profile_card_number_alter_profile_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_number',
            field=models.CharField(blank=True, max_length=166650),
        ),
    ]
