# Generated by Django 4.0.6 on 2022-08-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0026_alter_profile_card_number_alter_profile_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='telephone',
            new_name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='job',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill',
        ),
    ]
