# Generated by Django 4.0.6 on 2022-08-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0027_rename_telephone_profile_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_number',
            field=models.IntegerField(max_length=166650),
        ),
    ]
