# Generated by Django 4.0.6 on 2022-08-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0028_alter_profile_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_number',
            field=models.IntegerField(blank=True, default=2500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.IntegerField(blank=True, default=998931742328),
        ),
    ]
