# Generated by Django 4.0.6 on 2022-08-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0030_alter_profile_address_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='snapchat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
    ]
