# Generated by Django 4.0.6 on 2022-08-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0033_alter_contact_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=1, max_length=700),
            preserve_default=False,
        ),
    ]
