# Generated by Django 4.0.6 on 2022-08-31 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0034_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
