# Generated by Django 4.0.6 on 2022-09-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0038_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star_1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='star_2',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='product',
            name='star_3',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='product',
            name='star_4',
            field=models.IntegerField(default=5),
        ),
    ]
