# Generated by Django 4.0.6 on 2022-09-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0039_product_star_1_product_star_2_product_star_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='star_1',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='star_2',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='star_3',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='star_4',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
