# Generated by Django 4.0.6 on 2022-09-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0040_alter_product_price_alter_product_star_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star_5',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='star_4',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
