# Generated by Django 4.0.6 on 2022-09-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0042_ratestars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='star_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='star_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='star_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='star_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='star_5',
        ),
    ]
