# Generated by Django 4.0.6 on 2022-09-12 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0043_remove_product_star_1_remove_product_star_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratestars',
            name='img',
        ),
        migrations.RemoveField(
            model_name='ratestars',
            name='score',
        ),
        migrations.AddField(
            model_name='product',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
