# Generated by Django 4.0.6 on 2022-09-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0044_remove_ratestars_img_remove_ratestars_score_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RateStars',
        ),
    ]
