# Generated by Django 4.0.6 on 2022-09-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0045_delete_ratestars'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
