# Generated by Django 4.0.6 on 2022-09-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0046_product_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comment',
        ),
    ]
